
spring.datasource.url=jdbc:postgresql://localhost:5432/order_service
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

user.service.url=${USER_SERVICE_URL}

server.port=8083

logging.level.org.springframework.kafka: DEBUG
